import { Inter } from "next/font/google";
import "./globals.css";
import ClientAuthListener from "./components/clientAuthListener";
import OverlayAlert from "./components/overlayAlert";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientAuthListener />
        <OverlayAlert />
        {children}
        </body>
    </html>
  );
}
